### ISSUE TITLE
Tile Colour Does Not Update After Guess

### ISSUE THREAD

**Issue by ivanjjj** [alanrsoares/weirdle#1]
![Weirdle_Issue](https://user-images.githubusercontent.com/55337857/150925128-59127228-e7d2-4fee-8c12-a8f16e05213b.png)

After a guess has been submitted for a row and the application goes to a new row, the tile colours on the keyboard should refresh to reflect the most recent state (tile.variant)

**Comment by oieduardorabelo** [comment]
its a feature, not a bug
